@practice = Practice.create(name: "Podmedics Surgery")

User.create(name: "Steve", email: "steve@podmedics.com", password: "podmedics", password_confirmation: 'podmedics', admin: true, clinician: true, super_user: true, practice: @practice)
User.create(name: "Edward", email: "ed@example.com", password: "podmedics", password_confirmation: 'podmedics', clinician: true, practice: @practice)
User.create(name: "Reception", email: "info@example.com", password: "podmedics", password_confirmation: 'podmedics', admin: true, practice: @practice)
User.create(name: "Maureen", email: "memeagi@gmail.com", password: "podmedics", password_confirmation: 'podmedics', admin: true, super_user: true, clinician: true, practice: @practice)

@head_and_neck = Bodypart.create(name: 'Head and Neck')
@chest = Bodypart.create(name: 'Chest')
@abdomen = Bodypart.create(name: 'Abdomen')
@pelvis = Bodypart.create(name: 'Pelvis')
@shoulder_and_arms = Bodypart.create(name: 'Shoulder and Arms')
@hips_and_legs = Bodypart.create(name: 'Hips and Legs')
@back = Bodypart.create(name: 'Back')
@head_and_neck_rear = Bodypart.create(name: 'Head and Neck')
@shoulders_and_arms_rear = Bodypart.create(name: 'Shoulders and Arms')
@buttocks = Bodypart.create(name: 'Buttocks')
@upper_and_lower_legs = Bodypart.create(name: 'Upper and Lower Legs')

@headache = Presentation.create(name: 'Headache', bodypart: @head_and_neck)

@question1 = SurveyQuestion.create(question: "What part of the head?", presentation: @headache)
@question2 = SurveyQuestion.create(question: "How long have you had it in all?", presentation: @headache)
@question3 = SurveyQuestion.create(question: "Do you feel sick when you have it?", presentation: @headache)
@question4 = SurveyQuestion.create(question: "Do you vomit when the headache comes?", presentation: @headache)
@question5 = SurveyQuestion.create(question: "Do you have fuzzy lines in your vision when the headache comes?", presentation: @headache)
@question6 = SurveyQuestion.create(question: "What is the nature of this headache pain is it pounding or like a band?", presentation: @headache)
@question7 = SurveyQuestion.create(question: "What time of the day do you have this headache?", presentation: @headache)
@question8 = SurveyQuestion.create(question: "Do you have watering of the eyes with this headache?", presentation: @headache)
@question9 = SurveyQuestion.create(question: "Do you have difficulty with vision with this headache?", presentation: @headache)

@ear_pain = Presentation.create(name: 'Ear pain', bodypart: @head_and_neck)

@question10 = SurveyQuestion.create(question: "Which ear?", presentation: @ear_pain)
@question11 = SurveyQuestion.create(question: "How long?", presentation: @ear_pain)
@question12 = SurveyQuestion.create(question: "Any fever?", presentation: @ear_pain)
@question13 = SurveyQuestion.create(question: "Any dizziness?", presentation: @ear_pain)
@question14 = SurveyQuestion.create(question: "Any discharge?", presentation: @ear_pain)
@question15 = SurveyQuestion.create(question: "Difficulty with hearing?", presentation: @ear_pain)
@question16 = SurveyQuestion.create(question: "Any noises in the ear?", presentation: @ear_pain)
@question17 = SurveyQuestion.create(question: "Any nausea?", presentation: @ear_pain)
@question18 = SurveyQuestion.create(question: "Any vomiting?", presentation: @ear_pain)
@question19 = SurveyQuestion.create(question: "Blocked nose?", presentation: @ear_pain)

@pregnant = Presentation.create(name: 'Pregnant', bodypart: @abdomen)

@question20 = SurveyQuestion.create(question: "Date of last menstrual bleed (day1) - DD/MM/YYYY", presentation: @pregnant)
@question21 = SurveyQuestion.create(question: "Is this your first pregnancy?", presentation: @pregnant)
@question22 = SurveyQuestion.create(question: "How many children do you have?", presentation: @pregnant)
@question23 = SurveyQuestion.create(question: "Any previous miscarriages?", presentation: @pregnant)

@shoulder_pain = Presentation.create(name: 'Shoulder Pain', bodypart: @shoulder_and_arms)
@knee_pain = Presentation.create(name: 'Knee Pain', bodypart: @hips_and_legs)
@foot = Presentation.create(name: 'Painful toe', bodypart: @hips_and_legs)

@question2 = SurveyQuestion.create(question: "Have you dislocated it?", presentation: @shoulder_pain)
@question3 = SurveyQuestion.create(question: "Snapped your ACL?", presentation: @knee_pain)
@question4 = SurveyQuestion.create(question: "Too much red wine?", presentation: @foot)
@question4 = SurveyQuestion.create(question: "Played sport?", presentation: @foot)
@question4 = SurveyQuestion.create(question: "Fallen down the stairs?", presentation: @foot)
@question4 = SurveyQuestion.create(question: "Stubbed it?", presentation: @foot)
@question4 = SurveyQuestion.create(question: "Been walking on hot coals?", presentation: @foot)

@mandatory_question1 = SurveyQuestion.create(question: "What do you think is happening to you / going on?", mandatory: true)
@mandatory_question2 = SurveyQuestion.create(question: "What are you most worried about?", mandatory: true)
@mandatory_question3 = SurveyQuestion.create(question: "What were you hoping to gain from this appointment?", mandatory: true)
